# Generated by Django 3.1.3 on 2020-11-22 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Date from')),
                ('date_to', models.DateField(verbose_name='Date to')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
            },
        ),
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Absence type')),
            ],
            options={
                'verbose_name': 'AbsenceType',
                'verbose_name_plural': 'AbsenceTypes',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Date from')),
                ('date_to', models.DateField(verbose_name='Date to')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Base rate')),
                ('post_code', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Must be valid zipcode in formats 12345 or 12-345', regex='^(^[0-9]{2}(?:-[0-9]{3})?$)?$)')], verbose_name='Post code')),
                ('file_name', models.FileField(upload_to=None, verbose_name='File')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ContractType',
                'verbose_name_plural': 'ContractTypes',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('manager', models.CharField(max_length=256, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'JobPosition',
                'verbose_name_plural': 'JobPositions',
            },
        ),
    ]
