# Generated by Django 3.1.3 on 2020-11-22 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corehr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corehr.contracttype', verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corehr.department', verbose_name=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='job_postion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corehr.jobposition', verbose_name=''),
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corehr.absencetype', verbose_name=''),
        ),
        migrations.AddField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
