# Generated by Django 3.1.3 on 2021-01-06 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corehr', '0002_auto_20210106_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managers',
            options={'verbose_name': 'Managers', 'verbose_name_plural': 'Managers'},
        ),
        migrations.AlterField(
            model_name='absencetype',
            name='name',
            field=models.CharField(default='None', max_length=256, unique=True, verbose_name='Absence type'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(default='None', max_length=256, unique=True, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='None', max_length=256, unique=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='name',
            field=models.CharField(default='None', max_length=256, unique=True, verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='None', max_length=256, unique=True, verbose_name='Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('date_from', 'date_to', 'employee', 'absence_type')},
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('date_from', 'date_to', 'base_rate', 'post_code', 'file_name', 'job_position', 'contract_type', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='managers',
            unique_together={('manager', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('member_employee', 'organization')},
        ),
    ]
