# Generated by Django 3.1.3 on 2021-01-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corehr', '0003_auto_20210106_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corehr.contracttype', verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corehr.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='file_name',
            field=models.CharField(max_length=256, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corehr.jobposition', verbose_name='Job Position'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='post_code',
            field=models.CharField(max_length=9, verbose_name='Post code'),
        ),
    ]
